language: ruby
cache: bundler

before_install:
  - gem install bundler # need for jruby and ruby-head

rvm:
  - 2.3.1
  - 2.4.1
  - 2.5.3
  - 2.6.0
  - jruby-19mode
  - ruby-head
  - jruby-head

gemfile:
  - gemfiles/rails40_sprockets_2.gemfile
  - gemfiles/rails40_sprockets_3.gemfile
  - gemfiles/rails41_sprockets_2.gemfile
  - gemfiles/rails41_sprockets_3.gemfile
  - gemfiles/rails42_sprockets_2.gemfile
  - gemfiles/rails42_sprockets_3.gemfile
  - gemfiles/rails50_sprockets_3.gemfile
  - gemfiles/rails51_sprockets_3.gemfile

sudo: false

notifications:
  email:
    - agresso@gmail.com

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: ruby-head
    - rvm: jruby-head
  exclude:
    - rvm: 2.6.0
      gemfile: gemfiles/rails40_sprockets_2.gemfile # Segmentation fault
    - rvm: 2.6.0
      gemfile: gemfiles/rails40_sprockets_3.gemfile # Segmentation fault
    - rvm: 2.6.0
      gemfile: gemfiles/rails41_sprockets_2.gemfile # Segmentation fault
    - rvm: 2.6.0
      gemfile: gemfiles/rails41_sprockets_3.gemfile # Segmentation fault
    - rvm: 2.5.3
      gemfile: gemfiles/rails40_sprockets_2.gemfile # Segmentation fault
    - rvm: 2.5.3
      gemfile: gemfiles/rails40_sprockets_3.gemfile # Segmentation fault
    - rvm: 2.5.3
      gemfile: gemfiles/rails41_sprockets_2.gemfile # Segmentation fault
    - rvm: 2.5.3
      gemfile: gemfiles/rails41_sprockets_3.gemfile # Segmentation fault
    - rvm: 2.4.1
      gemfile: gemfiles/rails40_sprockets_2.gemfile # Segmentation fault
    - rvm: 2.4.1
      gemfile: gemfiles/rails40_sprockets_3.gemfile # Segmentation fault
    - rvm: 2.4.1
      gemfile: gemfiles/rails41_sprockets_2.gemfile # Segmentation fault
    - rvm: 2.4.1
      gemfile: gemfiles/rails41_sprockets_3.gemfile # Segmentation fault
